# ECTQG 2025 Registration and conference information

------------------------------------------------------------------------

The conference registration is now closed. 

For any questions, we are happy to help and answer via the conference e-mail address at [info\@ectqg.org](mailto:info@ectqg.org){.email}

## Registering to the conference

Early Bird registrations **until the 25th of June**, and after that full price registrations **until the 17th of July**. Please find below information on the registration process and related information.

You may register to the conference using the [Fienta ticketing service](https://fienta.com/ectqg-2025), where you can purchase an early bird conference registration ticket (full or student price) until the 25th of June or a full price registration ticket until the 17th of July.

The registration fees cover the welcome cocktail, all coffee-breaks and lunch on Thursday, Friday and Saturday, a Sunday bus excursion to Lahemaa, and the colloquium documentation.

## Conference information

### Conference dinner

On Friday the 12th, we warmly invite the conference participants to attend the conference dinner, held in Restoran SPOT in the historic Tallinn Old Town (Vanalinn). The dinner payment (70 euros, which includes a welcome drink, dinner and a glass of wine or other dinner drink) is separate, and can also be purchased [via Fienta](https://fienta.com/ectqg-2025) upon registration.

### Excursion

On Sunday the 14th, we are organizing a full day (approximately 9:30 am to 5:30pm) bus excursion to Lahemaa national park and Sagadi manor. The excursion is included in the registration fee, however, to estimate the resources needed to organize the excursion we ask for a separate registration [via Fienta](https://fienta.com/ectqg-2025).

### Accommodation

Conference participants register for accommodation themselves. We have group price arrangements with two hotels in Tallinn.

##### 1) Hampton by Hilton Tallinn

Single room: €79/night

Double room: €79/night

*Rate includes: breakfast, VAT, 24/7 access to hotel gym. Eligible to collect Hilton Honors points.*

Reservations: [sales\@hamptontallinn.com](mailto:sales@hamptontallinn.com){.email}, tel: +372 6205222 or [Booking link: Hampton Hilton Tallinn](https://www.hilton.com/en/book/reservation/rooms/?ctyhocn=TTLEEHX&arrivalDate=2025-09-10&departureDate=2025-09-14&groupCode=gy6&room1NumAdults=1)

Code: ECTQG2025

Free cancellation: 72 hrs prior to arrival.

[Hotel website](https://www.hilton.com/en/hotels/ttleehx-hampton-tallinn/)

##### 2) Mercure Tallinn

Single room: €110/night

Double room: €120/night

*Prices include accommodation, a rich buffet breakfast, parking, gym access, Wi-Fi, and VAT. You can cancel your room free of charge up to 14 days before the arrival date.*

To book, please send a room reservation email with the code ECTQG2025 to [cathi.kokk\@accor.com](mailto:cathi.kokk@accor.com){.email}.

[Hotel website](https://www.mercuretallinn.com/en/)
