# ECTQG 2025 Important dates and calls

**Long abstracts submission**

-   from February 10th to  [**April 15th**]{style="color: gold"} (via [EasyChair](https://easychair.org/my/conference?conf=ectqg2025))

**Colloquium registration and payments**

-   via Fienta - link to event to be shared later here and via e-mail
-   Early bird registration with a reduced fee: from May 15th to June 15th
-   Full registration: from June 16th to July 15th

## OPEN NOW: Call for Abstracts

We are very pleased to announce that the **Call for Abstracts** for the **European Colloquium on Theoretical and Quantitative Geography** in Tallinn 10th-14th September 2025. 

The call is [**EXTENDED TO 30th of April 2025**]{style="color: gold"}. Submissions are welcome for any topic of interest in quantitative and theoretical geography. In addition, 6 specifically organised sessions have been accepted, which we encourage you to consider while submitting your abstract. The list of Special Sessions can be found [behind this link](https://ectqg.org/2025/2025_special_sessions.html) on the conference website.

Abstracts submission takes place via the EasyChair platform: [ECTQG 2025](https://easychair.org/my/conference?conf=ectqg2025). Submission instructions can be found below. Each abstract should have between 400 and 800 words. A speaker must be indicated among the listed authors and there is a limit on 2 proposals as a speaker.

Stay tuned for additional information soon about the plenary talks!

We are looking forward to seeing many of you in Estonia.

Should you have any question related to the submission, please do not hesitate to contact us by email at [info\@ectqg.org](mailto:info@ectqg.org)

Happy submissions!

The ECTQG 2025 organisers

### How to submit an abstract

Abstracts for the ECTQG 2025 conference can be submitted via the EasyChair service.

1\. Navigate to <https://easychair.org/my/conference?conf=ectqg2025> on your browser

2\. Create an account by clicking "Create account". After confirming the account in your e-mail service, log in using the same link above

3\. Under ”Author”, click ”make a new submission”

4\. Fill in author details and your abstract submission

5\. Remember to click ”Submit” at the bottom of the page

6\. You may edit your submission by logging in using the same conference link above, navigating to “author”, under "Author", and then clicking “update information” or “update authors” in the top right corner of your submission.

If you wish to submit a second abstract, log in to the conference, click “author” under “Author” and click “New submission” located in the top navigation bar.
