# ECTQG 2025 Important dates and calls

**OPEN: Special Session / Workshop proposals**

-   from December 12th to **(extended!) January 31st ** (by email to **info\@ectqg.org**)

**Long abstracts submission**

-   from January 31st to **March 31st** (via EasyChair)

**Colloquium registration and payments**

-   Early bird registration with a reduced fee: from May 15th to June 15th
-   Full registration: from June 16th to July 15th

## Call for Special Sessions and Workshops

The 24th European Colloquium on Theoretical and Quantitative Geography (ECTQG) will take place in Tallinn, Estonia from the 10th to 14th of September 2025.

We are pleased to inform you that the call for special sessions and workshops is now open from **December 12th** and is open until the **15th of January 2025**.

Special Sessions will have between 4 and 6 registered participants. A Special Session must address a hot theoretical, methodological, or thematic issues within the ECTQG scope.

Submissions can be made via e-mail to **info\@ectqg.org** Please include the following information:

-   the name(s) of the organiser(s)

-   a short title for the session

-   a half-page description of its scope

-   intentions and plans to publish a special issue in a journal

Each accepted Special Session will be listed and described on the website. At the time of abstract submissions, researchers will be able to attach their abstract to an accepted Special Session or will be allocated to general themes of the ECTQG. The organiser(s) of the Special Session will be in charge of abstracts selection after registration and a pre-screening from the Local Scientific Committee.

All necessary information such as important dates will be updated here.

Should you have any question related to the submission, please do not hesitate to contact us by e-mail at **info\@ectqg.org**.

We are looking forward to your proposals!
