# List of past ECTQG colloquia

-   24th [Tallinn](2025/2025_welcome.html), Estonia, 2025

-   23rd [Braga](https://ucpages.uc.pt/events/ectqg2023), Portugal, 2023 ([pdf](pdfs/ectqg_2023_Braga_proceedings.pdf))

-   22nd [Manchester](https://ectqg2021.wordpress.com), United Kingdom, 2021 ([pdf](pdfs/ectqg_2021_Manchester_proceedings.pdf))

-   21st Mondorf-les-Bains, Luxembourg, 2019 ([pdf](pdfs/ectqg_2019_Mondorf_proceedings.pdf))

-   20th [York](https://www.geog.leeds.ac.uk/ectqg17), United Kingdom, 2017 ([pdf](pdfs/ectqg_2017_York_proceedings.pdf))

-   19th Bari, Italy, 2015

-   18th Dourdan, France, 2013

-   17th Athens, Greece, 2011

-   16th Maynooth, Ireland, 2009

-   15th Montreux, Switzerland, 2007

-   14th Tomar, Portugal, 2005

-   13th Lucca, Italy, 2003

-   12th Saint-Valéry-en-Caux, France, 2001

-   11th Durham, United Kingdom, 1999

-   10th Rostock, Germany, 1997

-   9th Spa, Belgium, 1995

-   8th Budapest Hungary, 1993

-   7th Stockholm, Sweden, 1991

-   6th Chantilly, France, 1989

-   5th Bardonecchia, Italy, 1987

-   4th Veldhoven, The Netherlands, 1985

-   3rd Augsburg, Germany, 1982

-   2nd Cambridge, United Kingdom, 1980

-   1st Strasbourg, France, 1978
