# Informal board and contacts {#sec-informal-board}

The ECTQG is a vibrant, non-institutionalized community that thrives on self-organization and collective effort. While there is no formal board, a dedicated group of individuals, including recent organizers, ensures the continuation of our colloquium through the years and meets to address day-to-day matters.

They are ready to answer most of your questions about the network. Please feel free to reach out to them or by sending an email to [info\@ectqg.org](mailto:info@ectqg.org)

-   [Antonio Antunes](mailto:antunes@dec.uc.pt)
-   [Geoffrey Caruso](mailto:geoffrey.caruso@uni.lu)
-   [Clémentine Cottineau](mailto:C.Cottineau@tudelft.nl)
-   [Giovanni Fusco](mailto:C.Cottineau@tudelft.nl)
-   [Didier Josselin](mailto:didier.josselin@univ-avignon.fr)
-   [Jenni Partanen](mailto:jenni.partanen@tut.fi)
-   [Nuno Pinto](mailto:nuno.pinto@manchester.ac.uk)
-   [Denise Pumain](mailto:pumain@parisgeo.cnrs.fr)
-   [Céline Rozenblat](mailto:celine.rozenblat@unil.ch)
-   [Isabelle Thomas](mailto:Isabelle.Thomas@uclouvain.be)
-   [Julie Vallée](mailto:julie.vallee@parisgeo.cnrs.fr)

The ECTQG community also relies on regular attendees and network friends from different countries who consistently bring their teams to the colloquium. They actively contribute ideas and proposals to promote the ECTQG community’s activities.

These individuals have agreed to be listed below so you can easily contact them for information. Please also don’t hesitate to reach out if you would also like to be listed here to support and communicate about the ECTQG.

-   *List of names in progress*
